@url = http://localhost:3000/api



### 
GET {{url}}/

###
GET {{url}}/commands?controller=EC-LB-100-5110-01
Content-Type: application/json



###

###
PUT {{url}}/commands/EC-LB-100-5110-01
Content-Type: application/json


    {
    "code": "OPCOMMAND5",
    "value": "ON"

    
    }

  

###

###
POST {{url}}/commands
Content-Type: application/json


    {
    "code": "OPCOMMAND5",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    }


###
POST {{url}}/commands/bulk
Content-Type: application/json


    [{
    "code": "OPCOMMAND2",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
    "code": "OPCOMMAND3",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
    "code": "OPCOMMAND4",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
    "code": "OPCOMMAND6",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
    "code": "OPCOMMAND7",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
    "code": "OPCOMMAND8",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
    "code": "OPCOMMAND9",
    "value": "OFF",
    "controller": "EC-LB-100-5110-01"
    }
    
    
    
    ]

    





