@url = https://loadbank.simplocity.in/api



### 
GET {{url}}/devices/EC01

###
GET {{url}}/devices/EC-LB-100-5110-01
Content-Type: application/json



###

###
POST {{url}}/simdata
Content-Type: application/json

    {
        "id":"1",
    "device": "OP1",
    "type" : "Relay",
    "constroller": "EC-LB-100-5110-01"
    
    }

    



###


###
POST {{url}}/devices
Content-Type: application/json


    {
        "id":"2",
    "device": "OP2",
    "type" : "Relay",
    "controller": "EC-LB-100-5110-01"
    }

    

###
POST {{url}}/devices/bulk
Content-Type: application/json

// create multiple devices
    [
        {
            "id":1,
     "device_id":"1111",       
    "device": "IP2",
    "type" : "Relay",
    "state": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
        "id":2,
        "device_id":"1112",
    "device": "IP3",
    "type" : "Relay",
    "state": "OFF",
    "controller": "EC-LB-100-5110-01"
    }
    



    
    ]




