@url = http://localhost:3000/api



### 
GET {{url}}/

###
GET {{url}}/devices?controller=EC-LB-100-5110-01
Content-Type: application/json



###

###
PUT {{url}}/devices/EC-LB-100-5110-01
Content-Type: application/json

[
    {
    "device": "OP3",
    "state": "ON"
    
    },

    {
     "device": "OP4",
    "state": "OFF"
    
    }

]

###


###
POST {{url}}/devices
Content-Type: application/json


    {
    "device": "OP5",
    "type" : "Relay",
    "state": "OFF2",
    "controller": "CTR1"
    }

    

###
POST {{url}}/devices/bulk
Content-Type: application/json

// create multiple devices
    [
        {
    "device": "IP2",
    "type" : "Relay",
    "state": "OFF",
    "controller": "EC-LB-100-5110-01"
    },
    {
    "device": "IP3",
    "type" : "Relay",
    "state": "OFF",
    "controller": "EC-LB-100-5110-01"
    }
    



    
    ]




