services:
  mongo_db:
    container_name: mongodb-container_name
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017

  influx_db:
    container_name: influx_db_container
    image: influxdb:latest
    restart: always
    volumes:
      - influx_db:/data/influxdb
    ports:
      - 8086:8086

  app:
    build: .
    ports:
      - 5001:5001
    environment:
      PORT: 5001
      DATABASE_URL: mongodb://mongo_db:27017/lbiot
      INFLUXDB_URL: http://influx_db
    depends_on:
      - mongo_db
      - influx_db

volumes:
  mongo_db: {}
  influx_db: {}
